# Generated by Django 4.2.3 on 2023-07-14 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nannypets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('porte', models.CharField(choices=[(1, 'Porte pequeno'), (2, 'Porte médio'), (3, 'Porte grande')], max_length=1)),
                ('docil', models.BooleanField()),
                ('especie', models.CharField(choices=[(1, 'Cachorro'), (2, 'Gato')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
