# Generated by Django 4.2.3 on 2023-07-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nannypets', '0002_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pet_photos'),
        ),
    ]
