# Generated by Django 4.2.3 on 2023-07-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nannypets', '0003_pet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[(1, 'Cachorro'), (2, 'Gato')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='porte',
            field=models.IntegerField(choices=[(1, 'Porte pequeno'), (2, 'Porte médio'), (3, 'Porte grande')]),
        ),
    ]
