# Generated by Django 4.2.3 on 2023-07-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nannypets', '0004_alter_pet_especie_alter_pet_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.IntegerField(choices=[(1, 'Cachorro'), (2, 'Gato')]),
        ),
    ]
