# Generated by Django 4.2.3 on 2023-07-15 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nannypets', '0005_alter_pet_especie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('dias_disponiveis', models.IntegerField(choices=[(1, 'Domingo'), (2, 'Segunda-feira'), (3, 'Terça-feira'), (4, 'Quarta-feira'), (5, 'Quinta-feira'), (6, 'Sexta-feira'), (7, 'Sábado')])),
                ('valor_diaria', models.IntegerField(default=1)),
                ('preferencia_porte', models.IntegerField(choices=[(1, 'Pequeno porte'), (2, 'Médio porte'), (3, 'Grande porte')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
