# Generated by Django 4.2.3 on 2023-07-15 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nannypets', '0006_cuidador'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoHospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Aguardando'), (1, 'Rejeitada'), (2, 'Confirmada')], default=0)),
                ('dia_inicial', models.DateField(verbose_name='Data Inicial')),
                ('dia_final', models.DateField(verbose_name='Data final')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nannypets.cuidador')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nannypets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('situacao', models.BooleanField(default=False)),
                ('solicitacao_hospedagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nannypets.solicitacaohospedagem')),
            ],
        ),
    ]
