# Generated by Django 4.2.3 on 2023-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nannypets', '0007_solicitacaohospedagem_hospedagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagem',
            name='situacao',
            field=models.IntegerField(choices=[(0, 'Em andamento'), (1, 'Concluída')], default=0),
        ),
    ]
