# Generated by Django 4.2.3 on 2023-07-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nannypets', '0008_alter_hospedagem_situacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuidador',
            options={'ordering': ['user'], 'verbose_name': 'Cuidador', 'verbose_name_plural': 'Cuidadores'},
        ),
        migrations.AlterModelOptions(
            name='hospedagem',
            options={'verbose_name': 'Hospedagem', 'verbose_name_plural': 'Hospedagens'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['nome'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaohospedagem',
            options={'verbose_name': 'Solicitação de Hospedagem', 'verbose_name_plural': 'Solicitações de Hospedagem'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, upload_to='nannypets/pet_photos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mysite/nannypets/user_photos', verbose_name='foto'),
        ),
    ]
